/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnishell32_Shell32 */

#ifndef _Included_jnishell32_Shell32
#define _Included_jnishell32_Shell32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnishell32_Shell32
 * Method:    GetKnownFolderPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnishell32_Shell32_GetKnownFolderPath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
